version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/todolist-lab-8
    docker:
      - image: cimg/ruby:3.1-browsers
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest . --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME

      - run:
          name: run-docker-image
          command: docker run -p 3000:3000 -d $IMAGE_NAME


  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: deploy-application
          command:  ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\"; export IMAGE_NAME=\"$IMAGE_NAME\"; sudo rm -rf TodoList/; git clone https://github.com/DecGillen/TodoList; source TodoList/deploy.sh"
           